### ISSUE TITLE
Tried in other language

### ISSUE THREAD

**Issue by cuongnguyengit** [rishikksh20/FastSpeech2#26]
I tried to train FastSpeech2 in other language. In that step using MFA to get alignment, i dont know how to apply for my language?

**Comment by rishikksh20** [comment]
@cuongnguyengit you need to re-train MFA with your target language or use tacotron 2 for duration extraction.

**Comment by cuongnguyengit** [comment]
@rishikksh20 
Thanks for reply.

I find this command to train 
'mfa train corpus_directory dictionary_path output_directory'
but i dont understand about corpus_directory, dictionary_path.

And how many corpus_directory is enough? where I can find dictionary_path in?

Sorry because of detail question.
I hardly try to learn the TTS task.

**Comment by rishikksh20** [comment]
@karan-deepsync please look at the above question

**Comment by cuongnguyengit** [comment]
Can you help me fixing the problem?

Thanks

Vào 12:04, Th 2, 28 thg 12, 2020 Rishikesh (ऋषिकेश) <
notifications@github.com> đã viết:
