### ISSUE TITLE
Question about duration predictor.

### ISSUE THREAD

**Issue by Jackson-Kang** [rishikksh20/FastSpeech2#29]
Hello @rishikksh20 ,

First of all, thank you for sharing your awesome works such as FastSpeech2, VocGAN, AdaSpeech and etcs.
It helped me a lot.

I leave this question due to my curiosity about duration predictor improvements.
A few months ago, evaluation performance of duration predictor seemed to be not good due to overfitting. (train error: below 0.01, but eval error: 0.5~0.6.)

But, now it has been drastically improved (eval error 0.5~0.6  -> 0.06 ~ 0.08). 

If you don't mind, could you tell me what was the problem of your previous version of duration predictor?

Always appreciate,

**Comment by rishikksh20** [comment]
@Jackson-Kang I haven't updated this code repo for a while, which duration predictor you are talking about.

**Comment by Jackson-Kang** [comment]
I think I just confused with other repos.

Anyway, thank you for answering my question.
Sincerely,
