### ISSUE TITLE
hparams.py is missing in colabs

### ISSUE THREAD

**Issue by bthiban** [rishikksh20/FastSpeech2#31]
when running the code in colabs, hparams.py is missing.

`def synthesis(text, path):
    """Decode with E2E-TTS model."""
    
    print("TTS synthesis")
    # read training config
    idim = hp.symbol_len 
    odim = hp.num_mels
    model = FeedForwardTransformer(idim, odim)`

**Comment by carankt** [comment]
just add this code before your error cell
```
from utils.hparams import HParam  
hp = HParam("configs/default.yaml")  
```
